### ISSUE TITLE
finer grid toggle

### ISSUE THREAD

**Issue by whattheshark** [klugeinteractive/synth-riders-editor#10]
press (hotkey button) to toggle a finer grid to place notes on.

this will allow different shapes and finer control of spirals while maintaining circular evenly spaced patterns (if so desired)
![finergridmockup](https://user-images.githubusercontent.com/38573505/61161174-f0f7ef00-a4bf-11e9-9cd6-b4765ed3cff6.png)

**Comment by shogoki-vnz** [comment]
As version 1.8.1-4 pressing ALT + KEY+ or ALT + KEY- will change the snap grid size
