### ISSUE TITLE
option for comfort grid outline for better visibility

### ISSUE THREAD

**Issue by whattheshark** [klugeinteractive/synth-riders-editor#11]
small quality of life feature: being able to select your default comfort grid, between the current version and one that is an outline so you can more easily see the notes further down the timeline. 

optional: when toggling the comfort grid with hotkey G - it would only cycle between the selected default (opaque or outlines) and off

some people struggle to see which notes are on the current step of the timeline, which the current partially opaque comfort grid helps with, i would much prefer being able to have an outline of the comfort grid so i can see down the timeline but still assess where my notes are without memorizing the grid without comfort view :)
![whatabeautifulsilhouette](https://user-images.githubusercontent.com/38573505/61161389-c65a6600-a4c0-11e9-9695-3eaed51f32eb.png)

**Comment by shogoki-vnz** [comment]
As version 1.8.1-2 now pressing "CTRL+G" will iterate between three types of the Conform Guide
