### ISSUE TITLE
button to toggle on/off triplets and uneven steps

### ISSUE THREAD

**Issue by whattheshark** [klugeinteractive/synth-riders-editor#17]
the triplet step divisions will be fantastic for certain songs, others don't need them. it would be very convenient to be able to toggle off 1/3, 1/5, 1/6, 1/7 steps to make the amount of steps to get between 1/2, 1/4 and 1/8 as minimal as possible (and mapping songs without the need for those steps more convenient).

when you are constantly flipping between 1/1, 1/2, 1/4 and 1/8 the extra steps add up a lot.

**Comment by Zeks** [comment]
I think this should be changed to: "ability to create a set of used steps for a song and bake it into it"

**Comment by shogoki-vnz** [comment]
fixed in #21
