### ISSUE TITLE
Make notes and obstacles be able to change the position in the XYZ space

### ISSUE THREAD

**Issue by aben311** [klugeinteractive/synth-riders-editor#2]
Be able to select a note or an obstacle and be able to move around the grid (X and Y axis) or along the timeline (Z axis)

**Comment by whattheshark** [comment]
preferred function: hold alt and left click a note to drag it around. if dragging it along the timeline it snaps to the step division that is set (1/1, 1/2, 1/4, etc)

**Comment by Zeks** [comment]
Impossible until shogo implements the grid coordunates for them in the game's song data. There's simply nowhere to write them into currently even if it's done
