### ISSUE TITLE
be able to place notes in play mode (live mapping)

### ISSUE THREAD

**Issue by aben311** [klugeinteractive/synth-riders-editor#4]
Make note placing in play mode based on the number of steps that I previously selected

**Comment by whattheshark** [comment]
while the track is playing: left click (or button hotkey) to place notes that will snap to the nearest step division that is selected. ie. if 1/1 will snap to major timeline divisions, 1/2 would snap it to half steps, etc.

**Comment by Zeks** [comment]
already done in my latest version. notes are placed with N
for that matter I also added 0.25x speed
