### ISSUE TITLE
Edit lines after they are created

### ISSUE THREAD

**Issue by aben311** [klugeinteractive/synth-riders-editor#7]
Be able to edit the nodes of a line and add or delete nodes along the line

**Comment by whattheshark** [comment]
example:
Alt + left click to drag a node of the rail.
Ctrl + left click to select a node and then delete key.

**Comment by Zeks** [comment]
I think I have a fairly decent idea of how to implement painless rail editing, will see if I understand enough code todo it myself tomorrow. If I can't I will just detail it here.

**Comment by Zeks** [comment]
I will attempt to rework this part completely. It's not that rails need an editing mode, it's that rails node placement and rails edit should be the same thing. Full details can be seen on discord in #editor channel:
https://discordapp.com/channels/478994602410508288/526207793708007448/599433588559183903

alternatively I will describe my changes when I actually do those. Hopefully this will make the whole process much easier.

**Comment by Zeks** [comment]
https://github.com/Zeks/synth-riders-editor/releases/download/1.9.0b2/editor-1.9b02.7z

I will be refactoring the code before pushing 1.9 to main repository, meanwhile this is the current working version.
https://www.youtube.com/watch?v=J_IVHlhyz64 a description of the changes

**Comment by shogoki-vnz** [comment]
Implement in #26
